name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decrypt publish key
      env:
        - PUBLISHER_KEY_PASSPHRASE: ${{ secrets.PUBLISHER_KEY_PASSPHRASE }}
      run: ./decrypt-publisher-key.sh
    - name: Build with Gradle
      run: ./gradlew build -PversionCode="${GITHUB_RUN_NUMBER}"
